name: personal_budget
description: PB Gastos y Presupuesto.
publish_to: "none"
version: 0.1.0+20

environment:
  sdk: ^3.7.0-46.0.dev

dependencies:
  currency_text_input_formatter: ^2.2.6
  dropdown_search: ^6.0.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.2.2
  flutter_signin_button: ^2.0.0
  getwidget: ^4.0.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  omni_datetime_picker: ^2.0.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  uuid: ^4.5.1
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
