name: personal_budget
description: Personal Budget Gastos y Presupuesto.
publish_to: "none"
version: 0.1.0+6

environment:
  sdk: ">=3.0.0-277.0.dev <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  currency_text_input_formatter: ^2.1.9
  dropdown_search: ^5.0.6
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  flutter_sms_inbox: ^1.0.2
  getwidget: ^3.0.1
  google_sign_in: ^6.1.6
  http: ^0.13.5
  intl: ^0.18.0
  omni_datetime_picker: ^1.0.2
  permission_handler: ^10.2.0
  provider: ^6.0.5
  uuid: ^3.0.7
  webview_flutter: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
dependency_overrides:
  intl: ^0.18.0
flutter:
  uses-material-design: true
  assets:
    # Add assets from the images directory to the application.
    - assets/
    - .env
