// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAutMrSc_k0_jQaUdgZrJJBSuyGz8flYcs',
    appId: '1:1075452885509:web:0515618edad69ab4f03a6c',
    messagingSenderId: '1075452885509',
    projectId: 'personal-budget-plan',
    authDomain: 'personal-budget-plan.firebaseapp.com',
    storageBucket: 'personal-budget-plan.appspot.com',
    measurementId: 'G-VXNJX41TWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2OX3nRvGhNoykpCdkoKu0sYlfb2dDvp0',
    appId: '1:1075452885509:android:37b76c1e2833618bf03a6c',
    messagingSenderId: '1075452885509',
    projectId: 'personal-budget-plan',
    storageBucket: 'personal-budget-plan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiDSxHisFkW3rtgjKL50htDQcb9hIdEOw',
    appId: '1:1075452885509:ios:35f9f27a3a354403f03a6c',
    messagingSenderId: '1075452885509',
    projectId: 'personal-budget-plan',
    storageBucket: 'personal-budget-plan.appspot.com',
    iosClientId: '1075452885509-k8bclunl0umd9esoitdav6sahloifkcg.apps.googleusercontent.com',
    iosBundleId: 'com.rcabezas1.personalBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiDSxHisFkW3rtgjKL50htDQcb9hIdEOw',
    appId: '1:1075452885509:ios:5f37e6ccb60153ebf03a6c',
    messagingSenderId: '1075452885509',
    projectId: 'personal-budget-plan',
    storageBucket: 'personal-budget-plan.appspot.com',
    iosClientId: '1075452885509-bj83rkmqivo5cvsnfnpbdvvvmghu1e26.apps.googleusercontent.com',
    iosBundleId: 'com.rcabezas1.personalBudget.RunnerTests',
  );
}
